import matplotlib
import os
import re
import string
import math

matplotlib.use("TkAgg")  # Fixes some weird error
from matplotlib import pyplot as plt
import matplotlib.font_manager as fm
import numpy as np
import pandas as pd

import sys

sys.path.append(os.path.abspath(os.path.join(__file__, os.path.pardir, os.path.pardir)))
from test_list import mass_list

file_dir = os.path.dirname(__file__)
data_dir = os.path.join(os.path.dirname(file_dir), "data")
DP_data_folder = "depth_profiles_hex"
DP_file_name = "a23925_1.txt"

sputter_rates = [0.11, 0.11, 0.08, 0.08, 0.07]
x_range = [0, 25]
y_range = [0, 1.1]

output_file_name = "S150_13Cr200oC_modeldiesel200oC.pdf"

species_to_plot_1 = [
    "Fe-",
    "Si_2-",
    "Cr-",
    "C_3O-",
    "CrO-",
    "Cr_2O-",
    "Fe_3O_3H-",
    "Fe_3H_3-",
    "FeO-",
    "FeO_2-",
    "FeO_3-",
    "Fe_4O_4H-",
    "MnO-",
    "C_3H_3O_2-",
    "Fe_2O-",
    "Fe_3O-",
    "Cr_2O_5-",
    "Fe_2O_2-",
    "Fe_3O_3-",
    "Fe_4O_4-",
    "NiO-",
    "Ni-",
    "SO_2-",
    "CCr-",
    "^53CrO-",
    "^54FeO-",
    "C_2H_3O_2-",
    "Fe_3O_2H-",
    "Fe_3-",
    "Cr_2O_4-",
    "SiCs-",
    "C_2-",
    "C_2H-",
    "CN-",
    "Si-",
    "^29Si-",
    "^30Si-",
    "O_2-",
    "O_2H-",
    "^34S-",
    "Cl-",
    "C_3-",
    "^37Cl-",
    "C_3H-",
    "C_3H_2-",
    "C_3H_3-",
    "C_2O-",
    "C_2HO-",
    "CO_2-",
    "CHO_2-",
    "NO_2-",
    "SO-",
    "O_3-",
    "C_4-",
    "C_4H-",
    "^50Cr-",
    "^34SO-",
    "C_4H_3-",
    "H_3O_3-",
    "CK-",
    "^53Cr-",
    "C_3HO-",
    "^54Fe-",
    "^54FeH-",
    "C_3H_3O-",
    "FeH-",
    "C_2H_2O_2-",
    "Co-",
    "CO_3-",
    "SiO_2-",
    "^60Ni-",
    "^61Ni-",
    "C_5H-",
    "^30SiO_2-",
    "Cu-",
    "^65Cu-",
    "C_4HO-",
    "C_5H_5-",
    "^50CrO-",
    "CHOK-",
    "C_3HO_2-",
    "^57FeO-",
    "SiSO-",
    "SiO_3-",
    "CoH_2O-",
    "SiHO_3-",
    "^60NiH_2O-",
    "CH_2S_2-",
    "CuO-",
    "COCr-",
    "SO_3-",
    "SO_3H-",
    "CuH_2O-",
    "^50CrO_2-",
    "^66ZnO-",
    "SiOK-",
    "Si_3-",
    "FeNO-",
    "MnS-",
    "MnO_2-",
    "MnH_2S-",
    "FeH_2S-",
    "FeH_3S-",
    "SiSO_2-",
    "C_5HO_2-",
    "C_2H_9O_2Si-",
    "C_2Cl_2-",
    "CH_7O_3Si-",
    "CuO_2H-",
    "Si_2C_2O-",
    "SO_4H-",
    "Si_3CH-",
    "FeSO-",
    "^54FeFe-",
    "Fe_2-",
    "Si_3S-",
    "Ni_2-",
    "Si_2^29SiS-",
    "KCuO-",
    "ZrS-",
    "FeCl_2-",
    "Cu_2H-",
    "Fe_2OH-",
    "Cs-",
    "Si_2O_5-",
    "C_2HS_2O_3-",
    "Si_5-",
    "Si_5H-",
    "Cu_2O-",
    "Cu_2OH-",
    "Fe_2O_2H-",
    "Si_3^29SiO_2-",
    "^65Cu_2O-",
    "Fe_2H_3O_2-",
    "Fe_2H_5O_2-",
    "C_2H_2OFe_2-",
    "Si_5O-",
    "Cu_2O_2-",
    "Cu_2O_2H-",
    "Fe_2H_2O_3-",
    "Ni_2O_3-",
    "Ni_2O_3H-",
    "Ni_2H_2O_3-",
    "C_3HSO-",
    "Si_3H_3O-",
    "FeSNH-",
    "FeH_2O_3-",
    "Si_2C_3O-",
    "SiC_5H_4O-",
    "C_9H-",
    "C_2KNa_2-",
    "C_4H_3N_2O_2-",
    "Si_4H_2-",
    "C_5H_6O_3-",
    "FeCo-",
    "Si_2CO_3-",
    "SiC_6O-",
    "CH_2SO_2Ca-",
    "C_7H_4NO-",
    "Si_3H_3O_2-",
    "SiC_6H_5O-",
    "Si_3C_3H-",
    "SiC_6H_7O-",
    "C_11-",
    "Si_3SO-",
    "Si_3C_4H_2-",
    "SiC_3H_10O_4-",
    "Fe_2H_4O_2-",
    "FeSO_4H-",
    "C_2Cs-",
    "Cu_2S-",
    "C_6H_6O_5-",
    "NaCa_3OH-",
    "^65CuS-",
    "CuH_2S-",
    "CNOFe-",
    "CrO_3-",
    "Si_2^29SiO-",
    "Cl_2O_2-",
    "FePO-",
    "FeO_3H-",
    "Si_4H_3-",
    "Co_2O_3H-",
    "C_2H_2O_2Fe_2-",
    "CsK-",
    "CsCa-",
    "Ni_2O_4-",
    "CsCr-",
    "CsFe-",
    "CH_2OFe_3-",
    "Fe_3O_2-",
    "Na_3Cr_2O_4-",
    "C_3H_5O_6Fe_2-",
    "Cs_2-",
    "C_21H_43O_4-",
    "C_28H_53-",
    "Na_3S_2O_8-",
    "H-",
    "C-",
    "O-",
    "OH-",
    "H_2O-",
    "F-",
    "P-",
    "C_4H_3O-",
    "SiCH_4NO-",
    "C_6H_3-",
    "KNaOH-",
    "C_7H-",
    "Si_2^29Si-",
    "C_3HSO-",
    "Si_3H_3O-",
    "FeSNH-",
    "FeH_2O_3-",
    "Si_2C_3O-",
    "SiC_5H_4O-",
    "C_9H-",
    "C_2KNa_2-",
    "C_4H_3N_2O_2-",
    "Si_4H_2-",
    "C_5H_6O_3-",
    "FeCo-",
    "Si_2CO_3-",
    "SiC_6O-",
    "CH_2SO_2Ca-",
    "C_7H_4NO-",
    "Si_3H_3O_2-",
    "SiC_6H_5O-",
    "Si_3C_3H-",
    "SiC_6H_7O-",
    "C_11-",
    "Si_3SO-",
    "Si_3C_4H_2-",
    "SiC_3H_10O_4-",
    "Fe_2H_4O_2-",
    "FeSO_4H-",
    "C_2Cs-",
    "Cu_2S-",
    "C_6H_6O_5-",
    "NaCa_3OH-",
    "Cu_2H_2O_2-",
    "Cr_2FeH-",
    "Fe_2H_2O_3-.1",
    "C_9H_6O_3-",
    "FeSO_5H-",
    "Si_3HO_6-",
    "C_15H-",
    "K_2NaSO_3H-",
    "NaMg_4O_4-",
    "C_3OCs-",
    "CsKO-",
    "SiO_2Cs-",
    "MoS_3-",
    "CsZn-",
    "Na_3S_3O_2-",
    "Cr_3O_3-",
    "CH_3O_2Ca_4-",
    "Na_3S_3O_3-",
    "C_4O_2Na_6-",
    "Ca_4O_4H-",
    "Na_3S_2O_6-",
    "Na_3S_2O_7-",
    "KNa_2Cr_2O_4-",
    "Cs_2H-",
    "Cs_2Cl-",
    "Cr_4O_6-",
    "C_5NO-",
    "C_6H_4N-",
    "BO-",
    "NO-",
    "H_2S-",
    "S-",
    "C_2H_2N-",
    "C_2N-",
    "C_2HN-",
    "CaH-",
    "SiCH-",
    "CNO-",
    "CH_3S-",
    "C_3N-",
    "CONa-",
    "C_3H_2N-",
    "C_3H_2O-",
    "SiCN-",
    "CrH_3-",
    "C_2S-",
    "C_2HS-",
    "Si_2H-",
    "CSN-",
    "C_5-",
    "C^50Cr-",
    "^62Ni-",
    "C_5H_2-",
    "SiHO_2-",
    "PO_2-",
    "C^53Cr-",
    "CNK-",
    "H_2S_2-",
    "C_3NO-",
    "CHNCa-",
    "CMn-",
    "CH_3Fe-",
    "C_6-",
    "SiC_2H_5O-",
    "SiCH_3O_2-",
    "Si_2CH_8-",
    "C_6H_5-",
    "C_5H_2O-",
    "SiC_3HO-",
    "^81Br-",
    "C_3Na_2-",
    "C_7-",
    "C_7H_2-",
    "C_7H_3-",
    "CoS-",
    "C_6H_3O-",
    "C_7H_7-",
    "Na_2NO_2-",
    "C_4H_5ONa-",
    "C_3H_8O_3-",
    "C_5HS-",
    "CSNCl-",
    "Nb-",
    "SiCH_8NO_2-",
    "SiC_4H_2O-",
    "^95Mo-",
    "NaCaO_2-",
    "C_4HSN-",
    "C_8-",
    "CuHS-",
    "C_8H-",
    "C_4H_4Na_2-",
    "C_8H_3-",
    "CHNOFe-",
    "KCu-",
    "C_2H_4S_2N-",
    "NiSOH-",
    "SiCH_3S_2-",
    "KNaO_3-",
    "C_9H_2-",
    "C_8H_2N-",
    "Ca_2O_2H-",
    "Ni_2H-",
    "CHNO_2Ni-",
    "CH_2O_5Na-",
    "C_5H_9SO-",
    "C_10-",
    "C_2NO_2Cr-",
    "C_3H_8S_2N-",
    "CHS_2NO_2-",
    "^91ZrS-",
    "ZrH_2S-",
    "Si_2C_3O_2-",
    "NbS-",
    "Si_3CHN_2-",
    "C_10H_5-",
    "CH_3O^95Mo-",
    "I-",
    "C_8S-",
    "Si_2CH_3N_3O-",
    "C_2O_3NaCl-",
    "Zn^66Zn-",
    "C_2H_3O_2Cl^37Cl-",
    "C_11H-",
    "CsH-",
    "C_11H_2-",
    "SiC_3H_8O_4-",
    "SrSO-",
    "SnO-",
    "NbSO-",
    "S_2N_2O_3H-",
    "C_8H_5N_3-",
    "SiC_3HSNO_2-",
    "Si_4O_2-",
    "SiC_8H_5O-",
    "C_5N_5O-",
    "Co_2O_2H-",
    "Ni_2H_4O_2-",
    "CNCu_2-",
    "C_6H_3O_2Na_2-",
    "C_2H_2OFe_2-.1",
    "Cu^65CuCl-",
    "Co_2H_3O_3-",
    "C_14H-",
    "SiHO_2CaCl_2-",
    "AgSCl-",
    "Si_4HONa_2-",
    "CsAlO-",
    "CO_3K_3-",
    "SiHOCs-",
    "K_2NaSO_3-",
    "As_2O_2-",
    "As_2O_2H-",
    "AgSO_3-",
    "CsAlO_2-",
    "Si_7-",
    "CH_2OFe_3-.1",
    "C_8H_8PO_4-",
    "NaS_2O_7H-",
    "HO_9Si_2-",
    "C_13H_5O_3-",
    "NaH_2S_2O_8-",
    "CH_4As_3-",
    "BiO_2-",
    "Ag_2O_2-",
    "Nb_2O_4-",
    "CH-",
    "CH_2-",
    "CH_3-",
    "AlO-",
    "BO_2-",
    "CB-",
    "PO-",
    "AlO_2-",
    "C_5H_3-",
    "C_4HN-",
    "C_4O-",
    "SiH_6NO-",
    "C_3H_2NO-",
    "C_3HS-",
    "SiC_2H_2O-",
    "C_5O-",
    "C_5HO-",
    "CH_7O_2Si-",
    "C_4H_3S-",
    "CO_3Na-",
    "SiC_2H_5O_2-",
    "C_7H_5-",
    "SiC_2H_7N_3-",
    "C_6H_7Na-",
    "C_8H_7-",
    "C_7H_3O-",
    "C_6S-",
    "FeSO-.1",
    "C_2HO_5-",
    "GeS-",
    "AsHS-",
    "C_5H_5SO-",
    "C_9H_7-",
    "C_8H_3O-",
    "C_9H_8-",
    "SiCH_2N_2O_3-",
    "SiC_4H_11O_2-",
    "Si_4C-",
    "C_10H_4-",
    "C_9H_4N-",
    "C_6H_3N_2O_2-",
    "Si_4C_2H-",
    "C_2HO_5-",
    "GeS-",
    "AsHS-",
    "C_5H_5SO-",
    "C_9H_7-",
    "C_8H_3O-",
    "C_9H_8-",
    "SiCH_2N_2O_3-",
    "SiC_4H_11O_2-",
    "Si_4C-",
    "C_10H_4-",
    "C_9H_4N-",
    "C_6H_3N_2O_2-",
    "Si_4C_2H-",
    "C_11H_5-",
    "Si_4C_2H_2-",
    "AgS-",
    "C_8H_11S-",
    "C_5O_5-",
    "C_10H_6N-",
    "SiC_8HO-",
    "C_7H_9O_3-",
    "SiC_6N_3-",
    "C_7H_10O_3-",
    "CH_2S_2O_4-",
    "C_12-",
    "C_10H_8O-",
    "Si_4H_2S-",
    "C_12H_3-",
    "SiC_6SO-",
    "C_3H_3O_2K_2-",
    "Si_3C_4H_2O-",
    "C_10H_4O_2-",
    "C_6H_5O_5-",
    "C_7H_10O_4-",
    "C_9H_3O_3-",
    "C_9H_4O_3-",
    "C_13H_5-",
    "Si_3C_5HO-",
    "C_9H_8O_3-",
    "C_7HO_5-",
    "C_12H_7O-",
    "C_14-",
    "C_8H_8O_4-",
    "Co_2H_3O_3-.1",
    "C_13N-",
    "C_3H_7O_8-",
    "Cr_3OH-",
    "SiC_4H_5O_6-",
    "SiOCs-",
    "C_11H_3O_3-",
    "Cr_2O_5-.1",
    "C_8H_9O_5-",
    "C_7H_8NO_5-",
    "C_15H_8-",
    "C_9H_5O_5-",
    "C_16H_2-",
    "Si_4H_3O_5-",
    "Si_4O_6-",
    "NaS_2O_8H-",
    "C_18H-",
    "C_2O_8Na_3-",
    "CsSr-",
    "BiO-",
    "C_15H_32O-",
    "H_3O_9Si_3-",
    "C_15H_9O_3-",
    "C_11H_2O_5Si-",
    "C_7H_3O_8Si-",
    "C_3O_3Na_7-",
    "NaS_4O_6H-",
    "C_16H_28O_2-",
]

len_species_list = len(mass_list) / 10

number_of_plots = math.ceil(len_species_list)


fig_width = 7
mass_spectra_ar = 7 / 4
padding = [[0.7, 0.3], [0.5, 0.3]]  # padding = [[left, right], [bottom, top]]
horizontal_gap = 0.1
vertical_gap = 0.1
letter_padding = 0.03

spectra_width = fig_width - sum(padding[0])
spectra_height = spectra_width / mass_spectra_ar
fig_height = number_of_plots * (spectra_height + sum(padding[1]))

spectra_width_rel = spectra_width / fig_width
spectra_height_rel = spectra_height / fig_height
vertical_gap_rel = vertical_gap / fig_height
horizontal_gap_rel = horizontal_gap / fig_width
horizontal_padding_rel = [x / fig_width for x in padding[0]]
vertical_padding_rel = [x / fig_height for x in padding[1]]


fig = plt.figure(figsize=(fig_width, fig_height))

axs = np.array(
    [
        fig.add_axes(
            [
                horizontal_padding_rel[0],
                1
                - (
                    vertical_padding_rel[0]
                    + spectra_height_rel
                    + i * (spectra_height_rel + vertical_padding_rel[0])
                ),
                spectra_width_rel,
                spectra_height_rel,
            ]
        )
        for i in range(number_of_plots)
    ]
)


# Plot data
data = pd.read_csv(
    os.path.join(data_dir, DP_data_folder, DP_file_name),
    header=1,
    skiprows=[2, 3],
    sep="\t",
)


rate = sputter_rates[3]

for j in range(number_of_plots):
    ax = axs[j]
    species_range_low = 0 + (j * 10)
    species_range_high = 10 + (j * 10)
    for species in mass_list[species_range_low:species_range_high]:
        x_values = data[data.columns[0]][3:].values
        y_values = data[species][3:].values
        max_y_value = y_values.max()
        norm_y_values = y_values / max_y_value
        label = re.sub(r"\-", r"$^{-}$", re.sub(r"(\^|_)(\d+)", r"$\1{\2}$", species))
        ax.scatter(x_values * rate, norm_y_values, s=2, label=label)
        ax.legend(
            loc="upper right",
            bbox_to_anchor=(1 - (0.05 / mass_spectra_ar), 0.95),
            fancybox=False,
            prop={"size": 8},
            frameon=True,
            ncol=2,
            markerscale=2,
        )
    # max_y_value = max(y_values)
    # index_max = np.where(y_values == max_y_value)[0][0]
    # x_position = x_values[index_max]
    # x_position_distance = x_position * rate
    # ax.axvline(12.16, color="black", linewidth=0.75, dashes=(5, 5))
# if species < len(species_to_plot) - 1:
#     labels = [item.get_text() for item in ax.get_xticklabels()]
#     empty_string_labels = [""] * len(labels)
#     ax.set_xticklabels(empty_string_labels)
labels = [item.get_text() for item in ax.get_yticklabels()]
empty_string_labels = [""] * len(labels)
ax.set_xlim(x_range)
ax.set_ylim(y_range)
# if len(species_to_plot[species]) > 3:
#     num_col = 2
# else:
#     num_col = 1


ax.set_xlabel("Distance / nm")
ax.set_ylabel("Intensity / 10$^3$ counts")

fig.savefig(os.path.join(file_dir, output_file_name))
